// Package contract owns the Contract Epoch layer (spec §5.3–5.4):
// .orchestra/contract/EPOCH.yaml with versions, sha256 and owners of the
// frozen design artifacts, hash verification of WorkOrder contract_refs and
// the built-in Artifact Verify checks. The runtime maintains EPOCH.yaml —
// models never write it.
package contract

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/orchestra/orchestra/patch/fsutil"
)

// DirRel is the contract artifacts directory relative to the project root.
const DirRel = ".orchestra/contract"

// EpochFileRel is the epoch file path relative to the project root.
const EpochFileRel = ".orchestra/contract/EPOCH.yaml"

// Artifact is one frozen contract artifact entry in EPOCH.yaml.
type Artifact struct {
	Version int    `yaml:"version"`
	SHA256  string `yaml:"sha256"`
	Owner   string `yaml:"owner,omitempty"`
}

// Epoch mirrors EPOCH.yaml: a monotonic epoch counter plus per-artifact
// versions and hashes, keyed by file name inside .orchestra/contract/.
type Epoch struct {
	Epoch     int                 `yaml:"epoch"`
	Artifacts map[string]Artifact `yaml:"artifacts"`
}

// Ref is a WorkOrder contract reference: the artifact the Lead read when
// producing the WorkOrder, with the hash of that version.
type Ref struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

// Load reads EPOCH.yaml. A missing file is not an error: (nil, false, nil) —
// the contract layer is simply not adopted in this project yet.
func Load(projectRoot string) (*Epoch, bool, error) {
	data, err := os.ReadFile(filepath.Join(projectRoot, filepath.FromSlash(EpochFileRel)))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, false, nil
		}
		return nil, false, fmt.Errorf("read %s: %w", EpochFileRel, err)
	}
	var e Epoch
	if err := yaml.Unmarshal(data, &e); err != nil {
		return nil, false, fmt.Errorf("parse %s: %w", EpochFileRel, err)
	}
	return &e, true, nil
}

// Save writes EPOCH.yaml atomically.
func Save(projectRoot string, e *Epoch) error {
	if e == nil {
		return fmt.Errorf("nil epoch")
	}
	data, err := yaml.Marshal(e)
	if err != nil {
		return fmt.Errorf("marshal epoch: %w", err)
	}
	path := filepath.Join(projectRoot, filepath.FromSlash(EpochFileRel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return fsutil.AtomicWriteFile(path, data, 0o644)
}

// FileSHA256 returns the hex sha256 of a file.
func FileSHA256(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}

// UpdateArtifact re-hashes .orchestra/contract/{name}, bumps its version and
// the global epoch, and persists EPOCH.yaml. This is the runtime side of an
// accepted contract_change_request (spec §5.3): only the artifact owner may
// trigger it; ownership arbitration happens above this call.
func UpdateArtifact(projectRoot, name, owner string) (*Epoch, error) {
	name = strings.TrimSpace(name)
	if name == "" || strings.ContainsAny(name, `/\`) {
		return nil, fmt.Errorf("contract: artifact name must be a bare file name inside %s, got %q", DirRel, name)
	}
	sha, err := FileSHA256(filepath.Join(projectRoot, filepath.FromSlash(DirRel), name))
	if err != nil {
		return nil, fmt.Errorf("contract: hash %s: %w", name, err)
	}
	e, found, err := Load(projectRoot)
	if err != nil {
		return nil, err
	}
	if !found {
		e = &Epoch{}
	}
	if e.Artifacts == nil {
		e.Artifacts = map[string]Artifact{}
	}
	art := e.Artifacts[name]
	if art.SHA256 == sha {
		// No content change — idempotent, no epoch bump.
		if art.Owner == "" && owner != "" {
			art.Owner = owner
			e.Artifacts[name] = art
			if err := Save(projectRoot, e); err != nil {
				return nil, err
			}
		}
		return e, nil
	}
	art.Version++
	art.SHA256 = sha
	if owner != "" {
		art.Owner = owner
	}
	e.Artifacts[name] = art
	e.Epoch++
	if err := Save(projectRoot, e); err != nil {
		return nil, err
	}
	return e, nil
}

// artifactName maps a ref path (".orchestra/contract/Domain_Model.md" or a
// bare "Domain_Model.md") to the EPOCH.yaml key.
func artifactName(refPath string) string {
	p := strings.TrimPrefix(filepath.ToSlash(strings.TrimSpace(refPath)), "./")
	p = strings.TrimPrefix(p, DirRel+"/")
	return p
}

// VerifyRefs checks WorkOrder contract_refs against EPOCH.yaml. Any unknown
// artifact or hash mismatch fails with blocked_reason=stale_contract semantics
// (spec §5.3): the WorkOrder was produced against an older contract version
// and must be regenerated by its Lead.
func VerifyRefs(projectRoot string, refs []Ref) error {
	if len(refs) == 0 {
		return nil
	}
	e, found, err := Load(projectRoot)
	if err != nil {
		return err
	}
	if !found {
		return fmt.Errorf("stale_contract: WorkOrder carries contract_refs but %s does not exist; unblock: freeze the contract (stage 2.5) or drop the refs", EpochFileRel)
	}
	for _, r := range refs {
		name := artifactName(r.Path)
		if name == "" || strings.Contains(name, "/") {
			return fmt.Errorf("stale_contract: contract_ref path %q is not an artifact inside %s", r.Path, DirRel)
		}
		art, ok := e.Artifacts[name]
		if !ok {
			return fmt.Errorf("stale_contract: artifact %q is not registered in %s; unblock: owner runs contract update for it", name, EpochFileRel)
		}
		want := strings.ToLower(strings.TrimSpace(r.SHA256))
		if want == "" {
			return fmt.Errorf("stale_contract: contract_ref for %q has empty sha256", name)
		}
		if want != strings.ToLower(art.SHA256) {
			return fmt.Errorf("stale_contract: %q hash mismatch (WorkOrder %s… vs epoch %d %s…); unblock: Lead regenerates the WorkOrder against the current contract",
				name, shortHash(want), e.Epoch, shortHash(art.SHA256))
		}
	}
	return nil
}

func shortHash(s string) string {
	if len(s) > 12 {
		return s[:12]
	}
	return s
}
