package instrument

// LangConfig describes everything needed to instrument one language with OTel SDK.
type LangConfig struct {
	Name string
	// DetectFiles: presence of any of these files in the project root identifies the language.
	DetectFiles []string
	// Extensions used by CKG scanner (informational).
	Extensions []string
	// AlreadyInstrumentedMarker: if this string is found anywhere in the project, skip.
	AlreadyInstrumentedMarker string
	// TelemetryFile is written relative to the project root.
	TelemetryFile string
	// TelemetryTemplate is the content of TelemetryFile.
	// Supports one placeholder: {{MODULE}} — the detected module/package path.
	TelemetryTemplate string
	// InstallArgs is the full argument list for the package manager (e.g. ["get", "pkg@latest"]).
	InstallCmd  string   // binary: "go", "pip", "npm", …
	InstallArgs []string // args passed to InstallCmd
	// MainPatch describes how to patch the entry point.
	MainPatch MainPatch
}

// MainPatch describes the text surgery applied to the project entry point.
type MainPatch struct {
	// EntryGlobs are glob patterns searched (in order) for the entry point file.
	EntryGlobs []string
	// InsertAfter is the exact string after which the init call is inserted.
	InsertAfter string
	// InitCall is the line(s) to insert (with leading newline + tab).
	// Supports {{SERVICE}} placeholder (replaced by project dir name).
	InitCall string
	// ImportLine is the import path to inject into the import block.
	// Empty → no import injection attempted.
	ImportLine string
}

// Phase1Langs lists the Phase 1 languages: Go, Python, TypeScript/JS.
var Phase1Langs = []LangConfig{
	goLang,
	pythonLang,
	tsLang,
	jsLang,
}

// ---- Go ----

var goLang = LangConfig{
	Name:                      "go",
	DetectFiles:               []string{"go.mod"},
	Extensions:                []string{".go"},
	AlreadyInstrumentedMarker: "go.opentelemetry.io/otel",
	TelemetryFile:             "internal/telemetry/otel.go",
	TelemetryTemplate: `package telemetry

import (
	"context"
	"log"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
)

// InitTracer initialises an OTLP/HTTP trace exporter pointing at localhost:4318
// (the address used by orchestra runtime serve).
// Call it at the very start of main() and defer the returned shutdown function:
//
//	defer telemetry.InitTracer("my-service")()
func InitTracer(serviceName string) func() {
	exp, err := otlptracehttp.New(context.Background(),
		otlptracehttp.WithEndpoint("localhost:4318"),
		otlptracehttp.WithInsecure(),
	)
	if err != nil {
		log.Fatalf("otlp exporter: %v", err)
	}
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exp),
		sdktrace.WithResource(resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceName(serviceName),
		)),
	)
	otel.SetTracerProvider(tp)
	return func() { _ = tp.Shutdown(context.Background()) }
}
`,
	InstallCmd:  "go",
	InstallArgs: []string{"get", "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"},
	MainPatch: MainPatch{
		EntryGlobs:  []string{"main.go", "cmd/*/main.go", "cmd/main.go"},
		InsertAfter: "func main() {",
		InitCall:    "\n\tdefer telemetry.InitTracer(\"{{SERVICE}}\")()  // orchestra: OTel tracing\n",
		ImportLine:  "{{MODULE}}/internal/telemetry",
	},
}

// ---- Python ----

var pythonLang = LangConfig{
	Name:                      "python",
	DetectFiles:               []string{"requirements.txt", "pyproject.toml", "setup.py"},
	Extensions:                []string{".py"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "telemetry.py",
	TelemetryTemplate: `"""Orchestra OTel bootstrap — auto-generated by orchestra init --instrument."""
from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor


def init_tracer(service_name: str) -> None:
    """Configure OTLP/HTTP exporter pointing at localhost:4318 (orchestra runtime serve)."""
    resource = Resource.create({"service.name": service_name})
    provider = TracerProvider(resource=resource)
    exporter = OTLPSpanExporter(endpoint="http://localhost:4318/v1/traces")
    provider.add_span_processor(BatchSpanProcessor(exporter))
    trace.set_tracer_provider(provider)
`,
	InstallCmd:  "pip",
	InstallArgs: []string{"install", "opentelemetry-sdk", "opentelemetry-exporter-otlp-proto-http"},
	MainPatch: MainPatch{
		EntryGlobs:  []string{"main.py", "app.py", "run.py", "__main__.py"},
		InsertAfter: "if __name__ == \"__main__\":",
		InitCall:    "\n    from telemetry import init_tracer; init_tracer(\"{{SERVICE}}\")\n",
		ImportLine:  "",
	},
}

// ---- TypeScript ----

var tsLang = LangConfig{
	Name:                      "typescript",
	DetectFiles:               []string{"tsconfig.json"},
	Extensions:                []string{".ts"},
	AlreadyInstrumentedMarker: "@opentelemetry",
	TelemetryFile:             "telemetry.ts",
	TelemetryTemplate: `// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
// Load BEFORE your application code via:
//   ts-node -r ./telemetry.ts src/index.ts
//   node --require ./telemetry.js dist/index.js   (after tsc)
import { NodeSDK } from "@opentelemetry/sdk-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";
import { Resource } from "@opentelemetry/resources";
import { SemanticResourceAttributes } from "@opentelemetry/semantic-conventions";

const sdk = new NodeSDK({
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: process.env.OTEL_SERVICE_NAME ?? "{{SERVICE}}",
  }),
  traceExporter: new OTLPTraceExporter({
    url: "http://localhost:4318/v1/traces",
  }),
});
sdk.start();
process.on("SIGTERM", () => sdk.shutdown().finally(() => process.exit(0)));
`,
	InstallCmd: "npm",
	InstallArgs: []string{
		"install",
		"@opentelemetry/sdk-node",
		"@opentelemetry/exporter-trace-otlp-http",
		"@opentelemetry/resources",
		"@opentelemetry/semantic-conventions",
	},
	// TS/JS: loaded via --require, no code patching.
	MainPatch: MainPatch{},
}

// ---- JavaScript ----

var jsLang = LangConfig{
	Name:                      "javascript",
	DetectFiles:               []string{"package.json"},
	Extensions:                []string{".js"},
	AlreadyInstrumentedMarker: "@opentelemetry",
	TelemetryFile:             "telemetry.js",
	TelemetryTemplate: `// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
// Load BEFORE your application code via:
//   node --require ./telemetry.js index.js
const { NodeSDK } = require("@opentelemetry/sdk-node");
const { OTLPTraceExporter } = require("@opentelemetry/exporter-trace-otlp-http");
const { Resource } = require("@opentelemetry/resources");
const { SemanticResourceAttributes } = require("@opentelemetry/semantic-conventions");

const sdk = new NodeSDK({
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: process.env.OTEL_SERVICE_NAME ?? "{{SERVICE}}",
  }),
  traceExporter: new OTLPTraceExporter({
    url: "http://localhost:4318/v1/traces",
  }),
});
sdk.start();
process.on("SIGTERM", () => sdk.shutdown().finally(() => process.exit(0)));
`,
	InstallCmd: "npm",
	InstallArgs: []string{
		"install",
		"@opentelemetry/sdk-node",
		"@opentelemetry/exporter-trace-otlp-http",
		"@opentelemetry/resources",
		"@opentelemetry/semantic-conventions",
	},
	MainPatch: MainPatch{},
}
