package instrument

// LangConfig describes everything needed to instrument one language with OTel SDK.
type LangConfig struct {
	Name string
	// DetectFiles: presence of any of these files in the project root identifies the language.
	DetectFiles []string
	// Extensions used by CKG scanner (informational).
	Extensions []string
	// AlreadyInstrumentedMarker: if this string is found anywhere in the project, skip.
	AlreadyInstrumentedMarker string
	// TelemetryFile is written relative to the project root.
	TelemetryFile string
	// TelemetryTemplate is the content of TelemetryFile.
	// Supports one placeholder: {{MODULE}} — the detected module/package path.
	TelemetryTemplate string
	// InstallArgs is the full argument list for the package manager (e.g. ["get", "pkg@latest"]).
	InstallCmd  string   // binary: "go", "pip", "npm", …
	InstallArgs []string // args passed to InstallCmd
	// MainPatch describes how to patch the entry point.
	MainPatch MainPatch
}

// MainPatch describes the text surgery applied to the project entry point.
type MainPatch struct {
	// EntryGlobs are glob patterns searched (in order) for the entry point file.
	EntryGlobs []string
	// InsertAfter is the exact string after which the init call is inserted.
	InsertAfter string
	// InitCall is the line(s) to insert (with leading newline + tab).
	// Supports {{SERVICE}} placeholder (replaced by project dir name).
	InitCall string
	// ImportLine is the import path to inject into the import block.
	// Empty → no import injection attempted.
	ImportLine string
}

// Phase1Langs lists the Phase 1 languages: Go, Python, TypeScript/JS.
var Phase1Langs = []LangConfig{
	goLang,
	pythonLang,
	tsLang,
	jsLang,
}

// Phase2Langs lists the Phase 2 languages: Java, Kotlin, Scala, C#.
var Phase2Langs = []LangConfig{
	javaLang,
	kotlinLang,
	scalaLang,
	csharpLang,
}

// Phase3Langs lists the Phase 3 languages: Rust, Ruby, PHP, Elixir, C, C++.
var Phase3Langs = []LangConfig{
	rustLang,
	rubyLang,
	phpLang,
	elixirLang,
	clangLang,
	cppLang,
}

// AllLangs is the full union of phases 1–3.
var AllLangs = append(append(append([]LangConfig{}, Phase1Langs...), Phase2Langs...), Phase3Langs...)

// ---- Go ----

var goLang = LangConfig{
	Name:                      "go",
	DetectFiles:               []string{"go.mod"},
	Extensions:                []string{".go"},
	AlreadyInstrumentedMarker: "go.opentelemetry.io/otel",
	TelemetryFile:             "internal/telemetry/otel.go",
	TelemetryTemplate: `package telemetry

import (
	"context"
	"log"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
)

// InitTracer initialises an OTLP/HTTP trace exporter pointing at localhost:4318
// (the address used by orchestra runtime serve).
// Call it at the very start of main() and defer the returned shutdown function:
//
//	defer telemetry.InitTracer("my-service")()
func InitTracer(serviceName string) func() {
	exp, err := otlptracehttp.New(context.Background(),
		otlptracehttp.WithEndpoint("localhost:4318"),
		otlptracehttp.WithInsecure(),
	)
	if err != nil {
		log.Fatalf("otlp exporter: %v", err)
	}
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exp),
		sdktrace.WithResource(resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceName(serviceName),
		)),
	)
	otel.SetTracerProvider(tp)
	return func() { _ = tp.Shutdown(context.Background()) }
}
`,
	InstallCmd:  "go",
	InstallArgs: []string{"get", "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"},
	MainPatch: MainPatch{
		EntryGlobs:  []string{"main.go", "cmd/*/main.go", "cmd/main.go"},
		InsertAfter: "func main() {",
		InitCall:    "\n\tdefer telemetry.InitTracer(\"{{SERVICE}}\")()  // orchestra: OTel tracing\n",
		ImportLine:  "{{MODULE}}/internal/telemetry",
	},
}

// ---- Python ----

var pythonLang = LangConfig{
	Name:                      "python",
	DetectFiles:               []string{"requirements.txt", "pyproject.toml", "setup.py"},
	Extensions:                []string{".py"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "telemetry.py",
	TelemetryTemplate: `"""Orchestra OTel bootstrap — auto-generated by orchestra init --instrument."""
from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor


def init_tracer(service_name: str) -> None:
    """Configure OTLP/HTTP exporter pointing at localhost:4318 (orchestra runtime serve)."""
    resource = Resource.create({"service.name": service_name})
    provider = TracerProvider(resource=resource)
    exporter = OTLPSpanExporter(endpoint="http://localhost:4318/v1/traces")
    provider.add_span_processor(BatchSpanProcessor(exporter))
    trace.set_tracer_provider(provider)
`,
	InstallCmd:  "pip",
	InstallArgs: []string{"install", "opentelemetry-sdk", "opentelemetry-exporter-otlp-proto-http"},
	MainPatch: MainPatch{
		EntryGlobs:  []string{"main.py", "app.py", "run.py", "__main__.py"},
		InsertAfter: "if __name__ == \"__main__\":",
		InitCall:    "\n    from telemetry import init_tracer; init_tracer(\"{{SERVICE}}\")\n",
		ImportLine:  "",
	},
}

// ---- TypeScript ----

var tsLang = LangConfig{
	Name:                      "typescript",
	DetectFiles:               []string{"tsconfig.json"},
	Extensions:                []string{".ts"},
	AlreadyInstrumentedMarker: "@opentelemetry",
	TelemetryFile:             "telemetry.ts",
	TelemetryTemplate: `// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
// Load BEFORE your application code via:
//   ts-node -r ./telemetry.ts src/index.ts
//   node --require ./telemetry.js dist/index.js   (after tsc)
import { NodeSDK } from "@opentelemetry/sdk-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";
import { Resource } from "@opentelemetry/resources";
import { SemanticResourceAttributes } from "@opentelemetry/semantic-conventions";

const sdk = new NodeSDK({
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: process.env.OTEL_SERVICE_NAME ?? "{{SERVICE}}",
  }),
  traceExporter: new OTLPTraceExporter({
    url: "http://localhost:4318/v1/traces",
  }),
});
sdk.start();
process.on("SIGTERM", () => sdk.shutdown().finally(() => process.exit(0)));
`,
	InstallCmd: "npm",
	InstallArgs: []string{
		"install",
		"@opentelemetry/sdk-node",
		"@opentelemetry/exporter-trace-otlp-http",
		"@opentelemetry/resources",
		"@opentelemetry/semantic-conventions",
	},
	// TS/JS: loaded via --require, no code patching.
	MainPatch: MainPatch{},
}

// ---- JavaScript ----

var jsLang = LangConfig{
	Name:                      "javascript",
	DetectFiles:               []string{"package.json"},
	Extensions:                []string{".js"},
	AlreadyInstrumentedMarker: "@opentelemetry",
	TelemetryFile:             "telemetry.js",
	TelemetryTemplate: `// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
// Load BEFORE your application code via:
//   node --require ./telemetry.js index.js
const { NodeSDK } = require("@opentelemetry/sdk-node");
const { OTLPTraceExporter } = require("@opentelemetry/exporter-trace-otlp-http");
const { Resource } = require("@opentelemetry/resources");
const { SemanticResourceAttributes } = require("@opentelemetry/semantic-conventions");

const sdk = new NodeSDK({
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: process.env.OTEL_SERVICE_NAME ?? "{{SERVICE}}",
  }),
  traceExporter: new OTLPTraceExporter({
    url: "http://localhost:4318/v1/traces",
  }),
});
sdk.start();
process.on("SIGTERM", () => sdk.shutdown().finally(() => process.exit(0)));
`,
	InstallCmd: "npm",
	InstallArgs: []string{
		"install",
		"@opentelemetry/sdk-node",
		"@opentelemetry/exporter-trace-otlp-http",
		"@opentelemetry/resources",
		"@opentelemetry/semantic-conventions",
	},
	MainPatch: MainPatch{},
}

// ---- Java ----

var javaLang = LangConfig{
	Name:                      "java",
	DetectFiles:               []string{"pom.xml", "build.gradle", "build.gradle.kts"},
	Extensions:                []string{".java"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "src/main/java/telemetry/OtelConfig.java",
	TelemetryTemplate: `// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
// Add to pom.xml:
//   <dependency>
//     <groupId>io.opentelemetry</groupId>
//     <artifactId>opentelemetry-sdk</artifactId>
//     <version>1.38.0</version>
//   </dependency>
//   <dependency>
//     <groupId>io.opentelemetry</groupId>
//     <artifactId>opentelemetry-exporter-otlp</artifactId>
//     <version>1.38.0</version>
//   </dependency>
// For Gradle: implementation("io.opentelemetry:opentelemetry-sdk:1.38.0")
// Then call OtelConfig.init("{{SERVICE}}") at application startup.
package telemetry;

import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.exporter.otlp.http.trace.OtlpHttpSpanExporter;
import io.opentelemetry.sdk.OpenTelemetrySdk;
import io.opentelemetry.sdk.resources.Resource;
import io.opentelemetry.sdk.trace.SdkTracerProvider;
import io.opentelemetry.sdk.trace.export.BatchSpanProcessor;
import io.opentelemetry.semconv.resource.attributes.ResourceAttributes;

public class OtelConfig {
    public static OpenTelemetry init(String serviceName) {
        Resource resource = Resource.getDefault().merge(
            Resource.create(io.opentelemetry.api.common.Attributes.of(
                ResourceAttributes.SERVICE_NAME, serviceName)));
        OtlpHttpSpanExporter exporter = OtlpHttpSpanExporter.builder()
            .setEndpoint("http://localhost:4318/v1/traces")
            .build();
        SdkTracerProvider tracerProvider = SdkTracerProvider.builder()
            .addSpanProcessor(BatchSpanProcessor.builder(exporter).build())
            .setResource(resource)
            .build();
        OpenTelemetrySdk sdk = OpenTelemetrySdk.builder()
            .setTracerProvider(tracerProvider)
            .buildAndRegisterGlobal();
        Runtime.getRuntime().addShutdownHook(new Thread(tracerProvider::close));
        return sdk;
    }
}
`,
	InstallCmd:  "",
	InstallArgs: nil,
	MainPatch:   MainPatch{},
}

// ---- Kotlin ----

var kotlinLang = LangConfig{
	Name:                      "kotlin",
	DetectFiles:               []string{"build.gradle.kts", "settings.gradle.kts"},
	Extensions:                []string{".kt", ".kts"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "src/main/kotlin/telemetry/OtelConfig.kt",
	TelemetryTemplate: `// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
// Add to build.gradle.kts:
//   implementation("io.opentelemetry:opentelemetry-sdk:1.38.0")
//   implementation("io.opentelemetry:opentelemetry-exporter-otlp:1.38.0")
// Then call initTracer("{{SERVICE}}") at application startup.
package telemetry

import io.opentelemetry.api.OpenTelemetry
import io.opentelemetry.exporter.otlp.http.trace.OtlpHttpSpanExporter
import io.opentelemetry.sdk.OpenTelemetrySdk
import io.opentelemetry.sdk.resources.Resource
import io.opentelemetry.sdk.trace.SdkTracerProvider
import io.opentelemetry.sdk.trace.export.BatchSpanProcessor
import io.opentelemetry.semconv.resource.attributes.ResourceAttributes

fun initTracer(serviceName: String): OpenTelemetry {
    val resource = Resource.getDefault().merge(
        Resource.create(io.opentelemetry.api.common.Attributes.of(
            ResourceAttributes.SERVICE_NAME, serviceName)))
    val exporter = OtlpHttpSpanExporter.builder()
        .setEndpoint("http://localhost:4318/v1/traces")
        .build()
    val tracerProvider = SdkTracerProvider.builder()
        .addSpanProcessor(BatchSpanProcessor.builder(exporter).build())
        .setResource(resource)
        .build()
    val sdk = OpenTelemetrySdk.builder()
        .setTracerProvider(tracerProvider)
        .buildAndRegisterGlobal()
    Runtime.getRuntime().addShutdownHook(Thread { tracerProvider.close() })
    return sdk
}
`,
	InstallCmd:  "",
	InstallArgs: nil,
	MainPatch:   MainPatch{},
}

// ---- Scala ----

var scalaLang = LangConfig{
	Name:                      "scala",
	DetectFiles:               []string{"build.sbt", "project/build.properties"},
	Extensions:                []string{".scala"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "src/main/scala/telemetry/OtelConfig.scala",
	TelemetryTemplate: `// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
// Add to build.sbt:
//   libraryDependencies += "io.opentelemetry" % "opentelemetry-sdk" % "1.38.0"
//   libraryDependencies += "io.opentelemetry" % "opentelemetry-exporter-otlp" % "1.38.0"
// Then call OtelConfig.init("{{SERVICE}}") at application startup.
package telemetry

import io.opentelemetry.api.OpenTelemetry
import io.opentelemetry.exporter.otlp.http.trace.OtlpHttpSpanExporter
import io.opentelemetry.sdk.OpenTelemetrySdk
import io.opentelemetry.sdk.resources.Resource
import io.opentelemetry.sdk.trace.SdkTracerProvider
import io.opentelemetry.sdk.trace.export.BatchSpanProcessor
import io.opentelemetry.semconv.resource.attributes.ResourceAttributes

object OtelConfig {
  def init(serviceName: String): OpenTelemetry = {
    val resource = Resource.getDefault.merge(
      Resource.create(io.opentelemetry.api.common.Attributes.of(
        ResourceAttributes.SERVICE_NAME, serviceName)))
    val exporter = OtlpHttpSpanExporter.builder()
      .setEndpoint("http://localhost:4318/v1/traces")
      .build()
    val tracerProvider = SdkTracerProvider.builder()
      .addSpanProcessor(BatchSpanProcessor.builder(exporter).build())
      .setResource(resource)
      .build()
    val sdk = OpenTelemetrySdk.builder()
      .setTracerProvider(tracerProvider)
      .buildAndRegisterGlobal()
    Runtime.getRuntime.addShutdownHook(new Thread(() => tracerProvider.close()))
    sdk
  }
}
`,
	InstallCmd:  "",
	InstallArgs: nil,
	MainPatch:   MainPatch{},
}

// ---- C# ----

var csharpLang = LangConfig{
	Name:                      "csharp",
	DetectFiles:               []string{"*.csproj", "*.sln"},
	Extensions:                []string{".cs"},
	AlreadyInstrumentedMarker: "OpenTelemetry",
	TelemetryFile:             "Telemetry/OtelConfig.cs",
	TelemetryTemplate: `// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
// Install: dotnet add package OpenTelemetry.Exporter.OpenTelemetryProtocol
// Call OtelConfig.Init("{{SERVICE}}") at application startup and dispose the result on exit.
using OpenTelemetry;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;

namespace Telemetry;

public static class OtelConfig
{
    public static TracerProvider Init(string serviceName)
    {
        return Sdk.CreateTracerProviderBuilder()
            .SetResourceBuilder(ResourceBuilder.CreateDefault()
                .AddService(serviceName))
            .AddOtlpExporter(opts =>
            {
                opts.Endpoint = new Uri("http://localhost:4318/v1/traces");
            })
            .Build()!;
    }
}
`,
	InstallCmd:  "dotnet",
	InstallArgs: []string{"add", "package", "OpenTelemetry.Exporter.OpenTelemetryProtocol"},
	MainPatch:   MainPatch{},
}

// ---- Rust ----

var rustLang = LangConfig{
	Name:                      "rust",
	DetectFiles:               []string{"Cargo.toml"},
	Extensions:                []string{".rs"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "src/telemetry.rs",
	TelemetryTemplate: `// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
// Add to Cargo.toml [dependencies]:
//   opentelemetry = { version = "0.23", features = ["trace"] }
//   opentelemetry-otlp = { version = "0.16", features = ["http-proto", "reqwest-client"] }
//   opentelemetry_sdk = { version = "0.23", features = ["rt-tokio"] }
// Then call telemetry::init_tracer("{{SERVICE}}") in main() before any tracing.
use opentelemetry::global;
use opentelemetry_otlp::WithExportConfig;
use opentelemetry_sdk::{runtime, trace::config, Resource};
use opentelemetry::KeyValue;

pub fn init_tracer(service_name: &'static str) -> opentelemetry_sdk::trace::Tracer {
    opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .http()
                .with_endpoint("http://localhost:4318/v1/traces"),
        )
        .with_trace_config(config().with_resource(
            Resource::new(vec![KeyValue::new("service.name", service_name)]),
        ))
        .install_batch(runtime::Tokio)
        .expect("OTel pipeline failed")
}

pub fn shutdown() {
    global::shutdown_tracer_provider();
}
`,
	InstallCmd:  "cargo",
	InstallArgs: []string{"add", "opentelemetry-otlp", "--features", "http-proto"},
	MainPatch:   MainPatch{},
}

// ---- Ruby ----

var rubyLang = LangConfig{
	Name:                      "ruby",
	DetectFiles:               []string{"Gemfile", "Gemfile.lock"},
	Extensions:                []string{".rb"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "lib/telemetry.rb",
	TelemetryTemplate: `# Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
# Add to Gemfile:
#   gem 'opentelemetry-sdk'
#   gem 'opentelemetry-exporter-otlp'
# Then run: bundle install
# Call OtelHelper.init_tracer('{{SERVICE}}') at application startup.
require 'opentelemetry/sdk'
require 'opentelemetry/exporter/otlp'

module OtelHelper
  def self.init_tracer(service_name)
    OpenTelemetry::SDK.configure do |c|
      c.service_name = service_name
      c.add_span_processor(
        OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
          OpenTelemetry::Exporter::OTLP::Exporter.new(
            endpoint: 'http://localhost:4318/v1/traces'
          )
        )
      )
    end
  end
end
`,
	InstallCmd:  "bundle",
	InstallArgs: []string{"add", "opentelemetry-sdk", "opentelemetry-exporter-otlp"},
	MainPatch:   MainPatch{},
}

// ---- PHP ----

var phpLang = LangConfig{
	Name:                      "php",
	DetectFiles:               []string{"composer.json"},
	Extensions:                []string{".php"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "src/Telemetry/OtelConfig.php",
	TelemetryTemplate: `<?php
// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
// Install: composer require open-telemetry/sdk open-telemetry/exporter-otlp
// Call OtelConfig::init('{{SERVICE}}') at application startup.

namespace Telemetry;

use OpenTelemetry\Contrib\Otlp\OtlpHttpTransportFactory;
use OpenTelemetry\Contrib\Otlp\SpanExporter;
use OpenTelemetry\SDK\Common\Attribute\Attributes;
use OpenTelemetry\SDK\Resource\ResourceInfo;
use OpenTelemetry\SDK\Resource\ResourceInfoFactory;
use OpenTelemetry\SDK\Trace\Sampler\AlwaysOnSampler;
use OpenTelemetry\SDK\Trace\SpanProcessor\BatchSpanProcessor;
use OpenTelemetry\SDK\Trace\TracerProvider;
use OpenTelemetry\SemConv\ResourceAttributes;

class OtelConfig
{
    public static function init(string $serviceName): TracerProvider
    {
        $transport = (new OtlpHttpTransportFactory())->create(
            'http://localhost:4318/v1/traces', 'application/x-protobuf');
        $exporter = new SpanExporter($transport);
        $resource = ResourceInfoFactory::emptyResource()->merge(
            ResourceInfo::create(Attributes::create([
                ResourceAttributes::SERVICE_NAME => $serviceName
            ]))
        );
        $tracerProvider = new TracerProvider(
            new BatchSpanProcessor($exporter),
            new AlwaysOnSampler(),
            $resource
        );
        \OpenTelemetry\API\Globals::registerInitializer(fn() => $tracerProvider);
        return $tracerProvider;
    }
}
`,
	InstallCmd:  "composer",
	InstallArgs: []string{"require", "open-telemetry/sdk", "open-telemetry/exporter-otlp"},
	MainPatch:   MainPatch{},
}

// ---- Elixir ----

var elixirLang = LangConfig{
	Name:                      "elixir",
	DetectFiles:               []string{"mix.exs"},
	Extensions:                []string{".ex", ".exs"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "lib/telemetry/otel.ex",
	TelemetryTemplate: `# Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
# Add to mix.exs deps:
#   {:opentelemetry_exporter, "~> 1.7"},
#   {:opentelemetry, "~> 1.3"},
#   {:opentelemetry_api, "~> 1.3"}
# Then run: mix deps.get
# Add to config/config.exs:
#   config :opentelemetry, :resource, service: %{name: "{{SERVICE}}"}
#   config :opentelemetry, :processors, [
#     otel_batch_processor: %{
#       exporter: {:opentelemetry_exporter, %{endpoints: [{:http, "localhost", 4318, []}]}}
#     }
#   ]
# Call Telemetry.Otel.setup() in your Application.start/2.
defmodule Telemetry.Otel do
  @moduledoc "Orchestra OTel initializer."

  def setup(service_name \\ "{{SERVICE}}") do
    :otel_resource.create(%{"service.name" => service_name})
  end
end
`,
	InstallCmd:  "",
	InstallArgs: nil,
	MainPatch:   MainPatch{},
}

// ---- C ----

var clangLang = LangConfig{
	Name:                      "c",
	DetectFiles:               []string{"CMakeLists.txt", "Makefile", "configure.ac", "meson.build"},
	Extensions:                []string{".c", ".h"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "telemetry/otel.c",
	TelemetryTemplate: `/* Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
 *
 * Requires the opentelemetry-c API wrapper from opentelemetry-cpp.
 * See: https://github.com/open-telemetry/opentelemetry-cpp
 *
 * CMake — link after installing via vcpkg or Conan:
 *   target_link_libraries({{SERVICE}}
 *     opentelemetry-cpp::trace
 *     opentelemetry-cpp::otlp_http_exporter)
 *
 * vcpkg:  vcpkg install opentelemetry-cpp
 * Conan:  conan install opentelemetry-cpp/...
 *
 * Call otel_init("{{SERVICE}}") in main(); call otel_shutdown() on exit.
 */
#include "opentelemetry/exporters/otlp/otlp_http_exporter_factory.h"
#include "opentelemetry/sdk/trace/tracer_provider_factory.h"
#include "opentelemetry/sdk/trace/batch_span_processor_factory.h"
#include "opentelemetry/sdk/resource/resource.h"
#include "opentelemetry/trace/provider.h"

#ifdef __cplusplus
extern "C" {
#endif

void otel_init(const char* service_name);
void otel_shutdown(void);

#ifdef __cplusplus
}

#include <string>

inline void otel_init(const char* service_name) {
    namespace otlp      = opentelemetry::exporter::otlp;
    namespace sdk_trace = opentelemetry::sdk::trace;
    namespace trace_api = opentelemetry::trace;
    namespace resource  = opentelemetry::sdk::resource;

    otlp::OtlpHttpExporterOptions opts;
    opts.url = "http://localhost:4318/v1/traces";
    auto exporter  = otlp::OtlpHttpExporterFactory::Create(opts);
    auto processor = sdk_trace::BatchSpanProcessorFactory::Create(std::move(exporter), {});
    auto res       = resource::Resource::Create({{"service.name", service_name}});
    auto provider  = sdk_trace::TracerProviderFactory::Create(std::move(processor), res);
    trace_api::Provider::SetTracerProvider(std::move(provider));
}

inline void otel_shutdown(void) {
    auto provider = opentelemetry::trace::Provider::GetTracerProvider();
    if (auto* p = dynamic_cast<opentelemetry::sdk::trace::TracerProvider*>(provider.get())) {
        p->Shutdown();
    }
}
#endif /* __cplusplus */
`,
	InstallCmd:  "",
	InstallArgs: nil,
	MainPatch:   MainPatch{},
}

// ---- C++ ----

var cppLang = LangConfig{
	Name:                      "cpp",
	DetectFiles:               []string{"CMakeLists.txt", "conanfile.txt", "vcpkg.json"},
	Extensions:                []string{".cpp", ".cc", ".cxx", ".hpp"},
	AlreadyInstrumentedMarker: "opentelemetry",
	TelemetryFile:             "telemetry/otel.hpp",
	TelemetryTemplate: `// Orchestra OTel bootstrap — auto-generated by orchestra init --instrument.
//
// Requires opentelemetry-cpp: https://github.com/open-telemetry/opentelemetry-cpp
//
// CMake:
//   find_package(opentelemetry-cpp CONFIG REQUIRED)
//   target_link_libraries({{SERVICE}}
//     opentelemetry-cpp::trace
//     opentelemetry-cpp::otlp_http_exporter)
//
// vcpkg: vcpkg install opentelemetry-cpp
// Conan: conan install opentelemetry-cpp/...
//
// Usage: #include "telemetry/otel.hpp"
//   int main() { otel::init("{{SERVICE}}"); ... otel::shutdown(); }
#pragma once
#include "opentelemetry/exporters/otlp/otlp_http_exporter_factory.h"
#include "opentelemetry/sdk/trace/batch_span_processor_factory.h"
#include "opentelemetry/sdk/trace/tracer_provider_factory.h"
#include "opentelemetry/sdk/resource/resource.h"
#include "opentelemetry/trace/provider.h"
#include <string>

namespace otel {

namespace otlp      = opentelemetry::exporter::otlp;
namespace sdk_trace = opentelemetry::sdk::trace;
namespace trace_api = opentelemetry::trace;
namespace resource  = opentelemetry::sdk::resource;

inline void init(const std::string& service_name) {
    otlp::OtlpHttpExporterOptions opts;
    opts.url = "http://localhost:4318/v1/traces";
    auto exporter  = otlp::OtlpHttpExporterFactory::Create(opts);
    auto processor = sdk_trace::BatchSpanProcessorFactory::Create(std::move(exporter), {});
    auto res       = resource::Resource::Create({{"service.name", service_name}});
    auto provider  = sdk_trace::TracerProviderFactory::Create(std::move(processor), res);
    trace_api::Provider::SetTracerProvider(std::move(provider));
}

inline void shutdown() {
    if (auto* p = dynamic_cast<sdk_trace::TracerProvider*>(
            trace_api::Provider::GetTracerProvider().get())) {
        p->Shutdown();
    }
}

} // namespace otel
`,
	InstallCmd:  "",
	InstallArgs: nil,
	MainPatch:   MainPatch{},
}
