// Package webui embeds the built browser UI served by `orchestra web`.
//
// static/ is generated by `node ui/web/scripts/bundle-web.mjs` and committed,
// the same arrangement ui/vscode uses for media/chat.bundle.js: the Go build
// must not depend on node being installed.
package webui

import (
	"embed"
	"io/fs"
)

//go:embed all:static
var static embed.FS

// Assets returns the built site rooted at static/, so "index.html" resolves.
func Assets() fs.FS {
	sub, err := fs.Sub(static, "static")
	if err != nil {
		// Only reachable if the embed directive above is edited wrongly.
		panic(err)
	}
	return sub
}
